parameters:

services:

  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Maris\Symfony\User\Controller\RegistrationController: ~ # Контроллер регистрации пользователя.
  Maris\Symfony\User\Controller\LoginController: ~        # Контролер авторизации пользователя.
  Maris\Symfony\User\Controller\AccountController: ~      # Контролер личного кабинета пользователя.
  Maris\Symfony\User\Controller\LogoutController: ~       # Контролер выхода из системы пользователя.
  Maris\Symfony\User\Controller\DeleteUserController: ~   # Контролер для удаления пользователя.

  Maris\Symfony\User\Security\LoginAuthenticator: ~ # Аутенфикатор

  Maris\Symfony\User\Repository\UserRepository:
    arguments:
      $registry: '@doctrine'
      $translator: '@translator'